### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by codecontemplator** [effyteva/Teva.Common.Cultures#1]
Hi,

Thanks for creating this library. Which license does it use?

https://help.github.com/en/articles/licensing-a-repository

Cheers

**Comment by effyteva** [comment]
Hi,

I've added a license file,
I guess that's the most free and open for all license :)

Effy

**Comment by codecontemplator** [comment]
Thank you!

**Comment by effyteva** [comment]
@codecontemplator Glad I could help :)
